#      _____   _                        _____                 _
#    / ____| | |                      / ____|               | |
#   | (___   | |__     ___    _ __   | (___    _   _   ___  | |_    ___   _ __ ___
#    \___ \  | '_ \   / _ \  | '_ \   \___ \  | | | | / __| | __|  / _ \ | '_ ` _ \
#    ____) | | | | | | (_) | | |_) |  ____) | | |_| | \__ \ | |_  |  __/ | | | | | |
#   |_____/  |_| |_|  \___/  | .__/  |_____/   \__, | |___/  \__|  \___| |_| |_| |_|
#                             | |                __/ |
#                             |_|               |___/
#
# ＢＹ ＢＬＸＣＫＤＥＶ
#

#Stelle die MySQL-Verbindung her

host: 'localhost'
user: 'root'
Database: 'coinsapi'
passwort: '123'